# docker-compose file for local dev only
version: "3"

services:
  cargo-web-node:
    image: node:latest
    volumes:
      - .:/var/www
    ports:
      - 3000:3000
    working_dir: /var/www
    environment:
      APP_ENV: "dev"
      APP_VERSION: "dev-server"
      APP_API_HOSTNAME: "http://api.dev.planetcargo.live:8080"
      APP_ASSET_PREFIX: "/static/"
      HOSTNAME: "dev"
    extra_hosts:
      api.dev.planetcargo.live: 172.19.0.1
    command:
#### For development ###########
      - "node_modules/webpack-dev-server/bin/webpack-dev-server.js"
      - "--config=webpack/client.config.js"
      - "--mode=development"
      - "--host=0.0.0.0"
      - "--watch"
      - "--watch-aggregate-timeout=300"
      - "--progress"
      - "--port=3000"
      - "--watch-poll=1000"
      - "--allowed-hosts=dev.planetcargo.live"
      - "--content-base=webpack/"
      - "--history-api-fallback=/"


#### For Testing prod server
#      - "sh"
#      - "-c"
#      - >
#        node_modules/webpack/bin/webpack.js --config webpack/client.config.js &&
#        node_modules/webpack/bin/webpack.js --config webpack/server.config.js &&
#        node server.js

  cargo-web-nginx:
    image: nginx:latest
    links:
      - cargo-web-node
    ports:
      - 80:80
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
